### ISSUE TITLE
Message events 

### ISSUE THREAD

**Issue by alkaest2002** [SparkPost/php-sparkpost#136]
Hi.
My goal is to retrieve specific message events from the API (i.e., all delivered messages with a certain template)

This isn't working as I was expecting:

**SOLUTION 1**

```
$object =
[
            'events'         => 'delivery',
            'from'           => $this->computeTime(strtotime($timeFrom)),
            'to'             => $this->computeTime(time()),
            'page'           => ($page) ? $page : 1,
            'per_page'       => 100,
            'template_ids'   => 'invitation,remind',
];

$response = $this->sparky->transmissions->get($this->endpoints['events'],  $object);

var_dump($response);

```

The API sends back the following error

`Exception 'SparkPost\SparkPostException' with message '{ "errors": [ { "message": "Invalid transmission id", "code": "2001" } ] }'`

This is the stack trace relative to spark post

```

Stack trace:
#0 /Users/alkaest2002/Dropbox/sites/gzts-lab/vendor/sparkpost/sparkpost/lib/SparkPost/SparkPost.php(78): SparkPost\SparkPost->syncRequest('GET', 'transmissions/h...', Array, Array)
#1 /Users/alkaest2002/Dropbox/sites/gzts-lab/vendor/sparkpost/sparkpost/lib/SparkPost/Resource.php(86): SparkPost\SparkPost->request('GET', 'transmissions/h...', Array, Array)
#2 /Users/alkaest2002/Dropbox/sites/gzts-lab/vendor/sparkpost/sparkpost/lib/SparkPost/Resource.php(36): SparkPost\Resource->request('GET', 'https://api.spa...', Array, Array)
#3 /Users/alkaest2002/Dropbox/sites/gzts-lab/components/mailer/sparkpost/Mailer.php(165): SparkPost\Resource->get('https://api.spa...', Array)


```
My current solution is to use a curl wrapper:

**SOLUTION 2**

```
//build configuration array
$object =
        [
            'events'         =>'delivery',
            'from'           => $this->computeTime(strtotime($timeFrom)),
            'to'             => $this->computeTime(time()),
            'page'           => ($page) ? $page : 1,
            'per_page'       => 100,
            'template_ids'   => 'invitation,remind',
        ];

//build page
$page = ($page) ? $page : $this->endpoints['events']
               .'?'.urldecode(http_build_query(array_filter($object)));

//get page data (i.e. collection of events) via curl
$pageData = json_decode($this->curl
            ->setOption(CURLOPT_HTTPHEADER, ["Authorization:" .$this->apikey])
            ->get($page));

var_dump($pageData);
```

The API server hands back the desired data.

Now, the question: why **SOLUTION 1** throws that error about the transmission ids?

Thanks.

**Comment by ewandennis** [comment]
In **Solution 1**, It looks like you are calling the `transmissions` endpoint with a `message-events` request.  Try:

```php
$this->sparky->request('GET', 'message-events', $object);
```

**Comment by alkaest2002** [comment]
Thanks for your quick reply :-) and yes, it did work.
